name: life_graph
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  freezed_annotation: ^2.4.1
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.1.2
  firebase_core: ^3.2.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: 2.0.1
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/SUIT-Bold.otf
          weight: 700
        - asset: assets/fonts/SUIT-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SUIT-Regular.otf
          weight: 400
        - asset: assets/fonts/SUIT-Light.otf
          weight: 300
    - family: GowunDodum
      fonts:
        - asset: assets/fonts/GowunDodum-Regular.ttf
          weight: 400
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
    - family: PetitFormalScript
      fonts:
        - asset: assets/fonts/PetitFormalScript-Regular.ttf
          weight: 400
    - family: Bellefair
      fonts:
        - asset: assets/fonts/Bellefair-Regular.ttf
          weight: 400